### ISSUE TITLE
Leetcode session cookie not found. Please login in browser.

### ISSUE THREAD

**Issue by SpringHan** [ianding1/leetcode.vim#42] opened 2020-05-01 08:11 UTC
I have already logged in my browser, but it still couldn't use it.
I think the options have been OK.
This is my settings:
```vim
let g:leetcode_china = 1
let g:leetcode_browser = 'chrome'
```

**Comment by tenfyzhong** [comment] 2020-06-03 02:52
Duplicate of #40

**Closed** 2023-11-22 07:52 UTC
