### ISSUE TITLE
Wrong state

### ISSUE THREAD

**Issue by gu18168** [ianding1/leetcode.vim#13] opened 2019-08-19 15:33 UTC
This problem has cropped up recently, when I use `LeetcodeTest`(see the below image), the preview window show `Accepted` state, but you can see the actual answer is different from expected answer. The `LeetcodeSubmit` command can display state correctly.

[example](https://i.loli.ma/pic/dfff99ddb5414ae7becac340dd9e9c36.png)

**Comment by ianding1** [comment] 2019-08-23 02:29
The issue is addressed in commit e3529e560fb58dd8d6ebf0961fdb37473c67ce45

**Closed by ianding1** 2019-08-23 02:29 UTC
